// spec: docs/09 §5.1(chase-graph 산출물 스키마·검증 룰)·§4.2-4(정수 km 결정성), docs/00 §11-D90·D91,
//       WT-CH-01
//
// build/chase-graph.ts의 순수 코어(buildChaseGraph/validateChaseGraph/디코더/렌더러)를 검증한다.
// ①실 데이터(un195) 통합 테스트 ②합성 소국가 fixture로 정렬·동률 해소·연결성 위반 등 개별 규칙 테스트.

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import type { Country, CountryId, DifficultyTier } from '@wt/shared';
import { buildDataset } from './build/pipeline';
import {
  CHASE_GRAPH_HOME_ELIGIBLE_MIN,
  CHASE_GRAPH_NEAREST_COUNT,
  buildChaseGraph,
  decodeMatrixKm,
  renderChaseGraphTs,
  validateChaseGraph,
  type ChaseGraphDataset,
} from './build/chase-graph';

const BUILT_AT = '2026-07-21T00:00:00.000Z';

function stubCountry(id: string, lat: number, lon: number, tier: DifficultyTier = 3): Country {
  return {
    id,
    iso3: `${id}X`,
    nameKo: id,
    nameEn: id,
    aliasesKo: [],
    aliasesEn: [],
    continent: 'asia',
    subregion: 'n/a',
    difficultyTier: tier,
    capitalKo: id,
    capitalEn: id,
    flagEmoji: '🏳️',
    population: 1,
    latlng: [lat, lon],
    mapFeatureId: null,
    acceptedInputsKo: [id],
    acceptedInputsEn: [id],
  };
}

function cloneGraph(g: ChaseGraphDataset): ChaseGraphDataset {
  return JSON.parse(JSON.stringify(g)) as ChaseGraphDataset;
}

// ── 실 데이터(un195) — build-data.ts와 동일 원천으로 실사 검증 ──────────────────────────
const realCountries = buildDataset().dataset.countries;
const realContentSets = JSON.parse(
  readFileSync(new URL('../overrides/content-sets.json', import.meta.url), 'utf8'),
) as { un195: string[]; extended: string[] };
const realUn195 = new Set<CountryId>(realContentSets.un195);
const realGraph = buildChaseGraph(realCountries, realUn195, BUILT_AT);

describe('buildChaseGraph — 실 데이터(un195, docs/09 §5.1)', () => {
  it('ids = un195 195개, 오름차순 정렬, nodes 키와 일치', () => {
    expect(realGraph.ids.length).toBe(195);
    expect(realGraph.ids).toEqual([...realGraph.ids].sort());
    expect(new Set(realGraph.ids)).toEqual(realUn195);
    expect(Object.keys(realGraph.nodes).length).toBe(195);
  });

  it('모든 노드 nearest 정확히 12개, 자기 자신 미포함', () => {
    for (const id of realGraph.ids) {
      const node = realGraph.nodes[id]!;
      expect(node.nearest.length).toBe(CHASE_GRAPH_NEAREST_COUNT);
      expect(node.nearest.some((n) => n.id === id)).toBe(false);
    }
  });

  it('schemaVersion·builtAt 고정', () => {
    expect(realGraph.schemaVersion).toBe(1);
    expect(realGraph.builtAt).toBe(BUILT_AT);
  });

  it('검증 룰 4종 전부 통과 + homeEligible >= 30(실측 50)', () => {
    const { homeEligibleCount } = validateChaseGraph(realGraph, realUn195);
    expect(homeEligibleCount).toBeGreaterThanOrEqual(CHASE_GRAPH_HOME_ELIGIBLE_MIN);
    expect(homeEligibleCount).toBe(50);
  });

  it('결정성 — 동일 입력 2회 실행 바이트 동일(JSON·생성 .ts 둘 다)', () => {
    const graph2 = buildChaseGraph(realCountries, realUn195, BUILT_AT);
    expect(JSON.stringify(graph2)).toBe(JSON.stringify(realGraph));
    expect(renderChaseGraphTs(graph2)).toBe(renderChaseGraphTs(realGraph));
  });

  it('행렬 디코드가 nearest km와 전수 일치(양방향 조회 동일)', () => {
    for (const id of realGraph.ids) {
      for (const n of realGraph.nodes[id]!.nearest) {
        expect(decodeMatrixKm(realGraph, id, n.id)).toBe(n.km);
        expect(decodeMatrixKm(realGraph, n.id, id)).toBe(n.km);
      }
    }
  });

  it('decodeMatrixKm(a, a) === 0', () => {
    expect(decodeMatrixKm(realGraph, 'KR', 'KR')).toBe(0);
  });

  it('decodeMatrixKm: 미지 ISO 코드는 throw', () => {
    expect(() => decodeMatrixKm(realGraph, 'ZZ', 'KR')).toThrow(/unknown id "ZZ"/);
    expect(() => decodeMatrixKm(realGraph, 'KR', 'ZZ')).toThrow(/unknown id "ZZ"/);
  });
});

describe('renderChaseGraphTs — 산출물 상단 주석(포맷 동결, §5.1)', () => {
  const rendered = renderChaseGraphTs(realGraph);

  it('AUTO-GENERATED 경고 + 포맷 스펙(오프셋 공식·디코더 소관) 명시', () => {
    expect(rendered).toMatch(/AUTO-GENERATED by tooling\/scripts\/build-data\.ts/);
    expect(rendered).toMatch(/DO NOT EDIT BY HAND/);
    expect(rendered).toMatch(/offset = i\*n - i\*\(i\+1\)\/2 \+ \(j - i - 1\)/);
    expect(rendered).toMatch(/WT-CH-02\(packages\/shared\/src\/chase\/graph\.ts\) 소관/);
  });

  it('타입 전용 import + CHASE_GRAPH export', () => {
    expect(rendered).toContain("import type { ChaseGraphDataset } from '../build/chase-graph';");
    expect(rendered).toMatch(/export const CHASE_GRAPH: ChaseGraphDataset = /);
  });

  it('본문이 유효한 JSON(원본 graph와 값 동치)', () => {
    // 헤더의 `import type { ChaseGraphDataset } ...` 줄에도 '{'가 있으므로 export 선언 마커
    // 이후부터 잘라야 실제 JSON 리터럴 시작점을 정확히 찾는다.
    const marker = 'export const CHASE_GRAPH: ChaseGraphDataset = ';
    const markerIdx = rendered.indexOf(marker);
    expect(markerIdx).toBeGreaterThan(-1);
    const body = rendered.slice(markerIdx + marker.length).replace(/;\s*$/, '');
    expect(JSON.parse(body)).toEqual(realGraph);
  });
});

describe('buildChaseGraph — 합성 fixture: 정렬·동률 해소(§4.2-2/D91-⑤)', () => {
  // AA(기준, lat0/lon0) + 12 근접국(동률쌍 1개 포함) + 1 원거리 아웃라이어 = 14개국.
  // AA 관점 nearest-12는 아웃라이어를 제외한 12개 근접국이어야 하고, 5° 동률쌍은 ISO 사전순.
  const countries = [
    stubCountry('AA', 0, 0),
    stubCountry('N01', 0, 1),
    stubCountry('N02', 0, 2),
    stubCountry('N03', 0, 3),
    stubCountry('N04', 0, 4),
    stubCountry('TIE_A', 0, 5),
    stubCountry('TIE_B', 0, -5), // TIE_A와 AA 기준 정확히 동일 거리(위도0, |dLon|=5 대칭)
    stubCountry('N06', 0, 6),
    stubCountry('N07', 0, 7),
    stubCountry('N08', 0, 8),
    stubCountry('N09', 0, 9),
    stubCountry('N10', 0, 10),
    stubCountry('N11', 0, 11),
    stubCountry('FAR', 0, 170), // 아웃라이어 — 훨씬 멀어서 AA의 nearest-12에서 제외되어야 함
  ];
  const ids = new Set(countries.map((c) => c.id));
  const graph = buildChaseGraph(countries, ids, BUILT_AT);
  const aaNearest = graph.nodes['AA']!.nearest;

  it('nearest 정확히 12개 — 13개 후보 중 최원거리(FAR) 1개 제외', () => {
    expect(aaNearest.length).toBe(12);
    expect(aaNearest.some((n) => n.id === 'FAR')).toBe(false);
  });

  it('km 오름차순 정렬', () => {
    for (let i = 1; i < aaNearest.length; i++) {
      expect(aaNearest[i]!.km).toBeGreaterThanOrEqual(aaNearest[i - 1]!.km);
    }
  });

  it('반올림 후 동률(TIE_A/TIE_B)은 ISO 사전순 — TIE_A가 먼저', () => {
    const tieA = aaNearest.find((n) => n.id === 'TIE_A')!;
    const tieB = aaNearest.find((n) => n.id === 'TIE_B')!;
    expect(tieA).toBeDefined();
    expect(tieB).toBeDefined();
    expect(tieA.km).toBe(tieB.km); // 동률 확인(위도0 대칭 → 완전 동일 haversine)
    const idxA = aaNearest.findIndex((n) => n.id === 'TIE_A');
    const idxB = aaNearest.findIndex((n) => n.id === 'TIE_B');
    expect(idxA).toBeLessThan(idxB);
  });

  it('homeEligible = difficultyTier <= 2 그대로 반영', () => {
    const withHome = buildChaseGraph(
      [stubCountry('HI', 0, 0, 1), stubCountry('LO', 0, 1, 5)],
      new Set(['HI', 'LO']),
      BUILT_AT,
    );
    expect(withHome.nodes['HI']!.homeEligible).toBe(true);
    expect(withHome.nodes['LO']!.homeEligible).toBe(false);
  });
});

describe('validateChaseGraph — 두 클러스터 완전 분리 시 연결성 위반(§5.1 검증②)', () => {
  it('그래프 비연결이면 throw', () => {
    // 각 13개국 클러스터(간격 1°, 서로 12개 이웃만 nearest-12로 채워짐) + 클러스터간 거리 ~180°
    // (실제 haversine으로도 클러스터 내부보다 압도적으로 멀어 nearest-12에 절대 들어오지 않는다).
    const clusterA = Array.from({ length: 13 }, (_, i) => stubCountry(`P${String(i).padStart(2, '0')}`, 0, i));
    const clusterB = Array.from({ length: 13 }, (_, i) => stubCountry(`Q${String(i).padStart(2, '0')}`, 0, 180 + i));
    const countries = [...clusterA, ...clusterB];
    const ids = new Set(countries.map((c) => c.id));
    const g = buildChaseGraph(countries, ids, BUILT_AT);

    // 사전 조건: 클러스터 내부 전용 인접(설계 의도 확인) — 실패 시 이 테스트 자체가 무의미해짐.
    for (const c of clusterA) expect(g.nodes[c.id]!.nearest.every((n) => n.id.startsWith('P'))).toBe(true);
    for (const c of clusterB) expect(g.nodes[c.id]!.nearest.every((n) => n.id.startsWith('Q'))).toBe(true);

    expect(() => validateChaseGraph(g, ids)).toThrow(/비연결/);
  });
});

describe('validateChaseGraph — 검증 룰 위반 시 throw(§5.1, 실 데이터 그래프 변형)', () => {
  it('① nearest.length가 12가 아니면 throw', () => {
    const g = cloneGraph(realGraph);
    g.nodes['KR']!.nearest.pop();
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/nearest\.length/);
  });

  it('① nearest에 자기 자신 포함 시 throw', () => {
    const g = cloneGraph(realGraph);
    g.nodes['KR']!.nearest[0] = { id: 'KR', km: 0 };
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/자기 자신/);
  });

  it('① nearest에 중복 국가 포함 시 throw', () => {
    const g = cloneGraph(realGraph);
    g.nodes['KR']!.nearest[1] = { ...g.nodes['KR']!.nearest[0]! };
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/중복/);
  });

  it('① nearest에 un195 밖 국가(TW) 포함 시 throw', () => {
    const g = cloneGraph(realGraph);
    g.nodes['KR']!.nearest[0] = { id: 'TW', km: 999 };
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/un195 밖/);
  });

  it('① nearest가 km 오름차순이 아니면 throw', () => {
    const g = cloneGraph(realGraph);
    const nearest = g.nodes['KR']!.nearest;
    expect(nearest[0]!.km).not.toBe(nearest[1]!.km); // 스왑이 실제로 순서를 깨는지 사전 확인
    const tmp = nearest[0]!;
    nearest[0] = nearest[1]!;
    nearest[1] = tmp;
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/오름차순/);
  });

  it('① node 자체가 누락되면 throw', () => {
    const g = cloneGraph(realGraph);
    delete (g.nodes as Record<string, unknown>)['KR'];
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/node 누락/);
  });

  it('ids에 중복이 있으면 throw', () => {
    const g = cloneGraph(realGraph);
    g.ids.push('KR'); // 이미 존재하는 id 재삽입 — idSet.size !== ids.length
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/중복 존재/);
  });

  it('ids 개수가 un195와 다르면 throw', () => {
    const g = cloneGraph(realGraph);
    g.ids.push('ZZ'); // 신규 id 추가 — 개수 195 -> 196, un195(195)와 size 불일치
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/ids !== un195/);
  });

  it('ids 개수는 같지만 집합 내용이 다르면 throw(.some 분기)', () => {
    const g = cloneGraph(realGraph);
    const idx = g.ids.indexOf('KR');
    g.ids[idx] = 'ZZ'; // KR -> ZZ 치환, 개수는 그대로 195(size 동일, 내용만 다름)
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/ids !== un195/);
  });

  it('② 그래프 ids가 비어있으면 throw', () => {
    const empty: ChaseGraphDataset = { schemaVersion: 1, builtAt: BUILT_AT, nodes: {}, ids: [], matrix: '' };
    expect(() => validateChaseGraph(empty, new Set())).toThrow(/비어있음/);
  });

  it('③ homeEligible < 30이면 throw', () => {
    const g = cloneGraph(realGraph);
    for (const id of g.ids) g.nodes[id]!.homeEligible = false;
    g.nodes[g.ids[0]!]!.homeEligible = true; // 1개만 true — 최소 30 미달
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/homeEligible/);
  });

  it('④ 행렬 바이트 길이 불일치 시 throw', () => {
    const g = cloneGraph(realGraph);
    g.matrix = Buffer.from(new Uint8Array(4)).toString('base64'); // 195*194/2*2 바이트에 훨씬 못 미침
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/바이트 길이/);
  });

  it('④ 행렬 값이 0 이하면 throw', () => {
    const g = cloneGraph(realGraph);
    const bytes = Buffer.from(g.matrix, 'base64');
    bytes.writeUInt16LE(0, 0); // 상삼각 첫 엔트리를 0으로 — 실제로는 발생 불가능한 거리
    g.matrix = bytes.toString('base64');
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/<= 0/);
  });

  it('④ 행렬 값이 nearest km와 불일치하면 throw', () => {
    const g = cloneGraph(realGraph);
    const n = g.ids.length;
    const count = (n * (n - 1)) / 2;
    const buf = new ArrayBuffer(count * 2);
    const view = new DataView(buf);
    for (let i = 0; i < count; i++) view.setUint16(i * 2, 1, true); // 전부 1km로 뭉갬
    g.matrix = Buffer.from(buf).toString('base64');
    expect(() => validateChaseGraph(g, realUn195)).toThrow(/nearest km\(.*\) != matrix km\(1\)/);
  });
});
