#!/usr/bin/env bash
# spec: WT-HOST-01 (Fable 5 승인, 리드 승인 완료) — `app` 컨테이너의 유일한 진입점.
#
# 순서(배포 순서 불변식 — CLAUDE.md "migrations apply → deploy"의 자기호스팅 등가물):
#   1) 필수 시크릿 검증(부재/더미값이면 기동 거부)
#   2) env → workers/api/.dev.vars 생성
#   3) D1 마이그레이션 적용(--local, 영속 볼륨)
#   4) wrangler dev exec(top-level wrangler.toml, [env.*] 아님)
set -euo pipefail

API_DIR="/app/workers/api"
DATA_DIR="/data"

log() { echo "[selfhost:entrypoint] $*"; }
fail() {
  echo "[selfhost:entrypoint] FATAL: $*" >&2
  exit 1
}

# "dev-secret-"으로 시작하는 값은 이 레포의 workers/api/.dev.vars(.example)에 박힌 로컬 전용
# 더미값이다(순수 wrangler dev 로컬 개발용, 커밋되어 있어도 안전하도록 일부러 이 접두사를 쓴다).
# 자기호스팅 인스턴스는 실제로 공인 도메인에 노출되는 실배포이므로 이 더미값이 그대로 넘어오면
# 즉시 거부한다 — 세션/런 토큰 위조가 가능해지는 심각한 취약점이기 때문에 경고만 남기고
# 넘어가는 선택지는 없다.
is_dummy() {
  case "$1" in
    dev-secret-*) return 0 ;;
    *) return 1 ;;
  esac
}

require_secret() {
  local name="$1"
  local value="${!name:-}"
  if [ -z "$value" ]; then
    fail "$name is not set. Copy tooling/selfhost/.env.example to .env and fill in a real random secret (see comments in that file for a generator one-liner), then re-run 'docker compose up'."
  fi
  if is_dummy "$value"; then
    fail "$name is set to a dev-only dummy value ('dev-secret-*', copied from workers/api/.dev.vars). This is a self-hosted deployment, not local 'pnpm dev' — generate a real random secret, e.g.: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\" and put it in tooling/selfhost/.env."
  fi
}

require_secret SESSION_HMAC_SECRET
require_secret RUN_HMAC_SECRET
require_secret DAILY_SALT

# SESSION_HMAC_SECRET_PREV은 선택 필드(키 로테이션 중에만 채운다) — 값이 있는데 더미면 거부,
# 비어 있으면(로테이션 중이 아니면) 통과.
if [ -n "${SESSION_HMAC_SECRET_PREV:-}" ] && is_dummy "${SESSION_HMAC_SECRET_PREV}"; then
  fail "SESSION_HMAC_SECRET_PREV is set to a dev-only dummy value ('dev-secret-*'). Leave it unset unless you are actively rotating SESSION_HMAC_SECRET with a real previous secret."
fi

log "secret validation passed (SESSION_HMAC_SECRET, RUN_HMAC_SECRET, DAILY_SALT all set to non-dummy values)."

# ---------------------------------------------------------------------------
# 2) env → workers/api/.dev.vars
# 이 파일이 workers/api/.dev.vars(레포에 커밋된 더미값 파일)를 덮어쓴다 — 컨테이너 안에서만
# 존재하고 이미지/볼륨 어디에도 커밋되지 않는다.
# ENVIRONMENT=prod: 이 인스턴스는 로컬 sandbox가 아니라 실제로 공개 도메인에 서빙되는 자기호스팅
# 프로덕션이다. wrangler.toml 최상위 [vars]는 ENVIRONMENT="dev"이지만 .dev.vars가 이를
# 덮어쓴다 — routes/health.ts의 `?fault=` 강제 실패 훅 등 "ENVIRONMENT!=='prod'에서만 허용"
# 가드가 실제로 잠기게 하려면 여기서 반드시 prod로 선언해야 한다.
# ---------------------------------------------------------------------------
DEV_VARS_FILE="${API_DIR}/.dev.vars"
{
  echo "# AUTO-GENERATED by tooling/selfhost/entrypoint.sh at container boot."
  echo "# Do not edit by hand, do not commit — regenerated from tooling/selfhost/.env every start."
  echo "SESSION_HMAC_SECRET=${SESSION_HMAC_SECRET}"
  echo "RUN_HMAC_SECRET=${RUN_HMAC_SECRET}"
  echo "DAILY_SALT=${DAILY_SALT}"
  # GOOGLE_CLIENT_ID(WT-AUTH-01): 서버 aud 검증값(공개값, 시크릿 아님). 미설정이면 wrangler.toml
  # [vars]의 커밋된 공개값이 그대로 쓰이지만, .dev.vars가 [vars]를 덮어쓰므로 .env에 설정돼 있으면
  # 명시적으로 기록해 둔다(다른 프로젝트 client ID로 교체하는 자기호스터 대응).
  if [ -n "${GOOGLE_CLIENT_ID:-}" ]; then
    echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
  fi
  if [ -n "${SESSION_HMAC_SECRET_PREV:-}" ]; then
    echo "SESSION_HMAC_SECRET_PREV=${SESSION_HMAC_SECRET_PREV}"
  fi
  if [ -n "${SENTRY_DSN:-}" ]; then
    echo "SENTRY_DSN=${SENTRY_DSN}"
  fi
  echo "ENVIRONMENT=prod"
  if [ -n "${PUBLIC_ORIGIN:-}" ]; then
    echo "PUBLIC_ORIGIN=${PUBLIC_ORIGIN}"
  fi
} > "$DEV_VARS_FILE"
chmod 600 "$DEV_VARS_FILE"
log "wrote ${DEV_VARS_FILE}"

mkdir -p "$DATA_DIR"
cd "$API_DIR"

# ---------------------------------------------------------------------------
# 3) D1 마이그레이션 적용 — 배포 순서 불변식: migrations apply → serve.
# top-level wrangler.toml의 database_name(wt-main-dev)을 그대로 쓴다([env.*]는 무시).
# --persist-to는 아래 wrangler dev와 동일한 named volume 경로여야 같은 로컬 D1 상태를 본다.
# ---------------------------------------------------------------------------
log "applying D1 migrations (wt-main-dev, --local, --persist-to ${DATA_DIR}) ..."
pnpm exec wrangler d1 migrations apply wt-main-dev --local --persist-to "$DATA_DIR"

# ---------------------------------------------------------------------------
# 4) wrangler dev exec — top-level 설정([env.*] 아님), --local이 기본이라 Cloudflare 인증 불요.
# --test-scheduled: 크론 수동 발화 라우트를 연다. [WT-HOST-01 실측 + 리드 승인] 문서상 경로인
# /__scheduled는 assets(run_worker_first에 없음)에 가로채져 SPA로 폴백할 뿐 event.cron 디스패치가
# 실행되지 않는다 — cron-ping 서비스는 대신 /cdn-cgi/handler/scheduled(assets 라우팅보다 아래
# 계층에서 처리되는 wrangler dev 실제 스케줄 트리거 엔드포인트, Host 헤더가 localhost/127.0.0.1
# 패턴이어야 함)를 curl로 찌른다 — 근거는 cron-ping/crontab 상단 주석. exec로 넘겨 이 스크립트의
# PID를 wrangler가 이어받게 한다(신호 전달·docker stop이 정상 종료되도록).
# ---------------------------------------------------------------------------
log "starting wrangler dev on 0.0.0.0:8787 (--persist-to ${DATA_DIR}, --test-scheduled) ..."
exec pnpm exec wrangler dev --ip 0.0.0.0 --port 8787 --persist-to "$DATA_DIR" --test-scheduled
