// spec: docs/06 §4.2(비속어/예약어 목록), docs/00 §11-D14, docs/07 WT-M3-05 구현 세부 지시 5
// (로더 주입형 리팩터 — Workers 번들에는 node:fs가 없으므로 빌드타임 스냅샷으로 주입한다)
//
// pnpm run build:moderation-snapshot 엔트리. packages/moderation의 저장소 커밋 .txt 3종
// (badwords.ko/en, allowwords.en)을 읽어 workers/api가 import할 수 있는 TS 상수 파일을 생성한다.
// 파싱 규칙은 @wt/moderation/src/filter.ts의 loadWordlist와 완전히 동일해야 한다(1행 1항목,
// `#` 시작·빈 행 무시) — 두 로더가 다른 파싱을 하면 Node(vitest)와 Workers(runtime)에서 같은
// 닉네임에 대해 다른 판정이 나올 수 있다(클라·서버 판정 패리티 원칙과 동형의 함정).
// 네트워크 0, 결정적 출력(입력 .txt가 그대로면 산출 파일도 바이트 단위로 동일).

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const REPO_ROOT = new URL('../../', import.meta.url);
const p = (rel: string) => fileURLToPath(new URL(rel, REPO_ROOT));

/** @wt/moderation/src/filter.ts의 loadWordlist와 동일 파싱 규칙 — 변경 시 양쪽을 함께 고칠 것. */
function loadWordlist(absPath: string): string[] {
  const raw = readFileSync(absPath, 'utf8');
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));
}

function tsStringArray(words: string[]): string {
  return `[\n${words.map((w) => `  ${JSON.stringify(w)},`).join('\n')}\n]`;
}

function main(): void {
  const ko = loadWordlist(p('packages/moderation/badwords.ko.txt'));
  const en = loadWordlist(p('packages/moderation/badwords.en.txt'));
  const allow = loadWordlist(p('packages/moderation/allowwords.en.txt'));

  const out = `// AUTO-GENERATED by tooling/scripts/build-moderation-snapshot.ts. DO NOT EDIT BY HAND.
// spec: docs/06 §4.2, docs/00 §11-D14, docs/07 WT-M3-05 — packages/moderation/*.txt의 빌드타임
// 스냅샷. workers/api는 node:fs가 없는 런타임이라 @wt/moderation/src/engine의 createFilter(...)에
// 이 배열을 직접 주입한다(@wt/moderation/src/filter.ts의 node:fs 기본 로더는 import하지 않는다).
// 원본을 고치려면 packages/moderation/badwords.*.txt / allowwords.en.txt를 편집한 뒤
// \`pnpm run build:moderation-snapshot\`으로 재생성할 것 — 이 파일 직접 편집 금지.

export const MODERATION_KO_BADWORDS: readonly string[] = ${tsStringArray(ko)};

export const MODERATION_EN_BADWORDS: readonly string[] = ${tsStringArray(en)};

export const MODERATION_EN_ALLOWLIST: readonly string[] = ${tsStringArray(allow)};
`;

  const outPath = p('workers/api/src/lib/moderation-wordlists.generated.ts');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out);
  console.log(`  wrote workers/api/src/lib/moderation-wordlists.generated.ts (ko=${ko.length}, en=${en.length}, allow=${allow.length})`);
}

main();
